import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar' | 'fr';
type Direction = 'ltr' | 'rtl';

interface LanguageContextType {
  language: Language;
  direction: Direction;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  "en": {
    "nav.treatments": "Treatments",
    "nav.howItWorks": "How It Works",
    "nav.doctors": "Doctors",
    "nav.stories": "Stories",
    "nav.travelGuide": "Travel Guide",
    "nav.faq": "FAQ",
    "nav.freeConsultation": "Free Consultation",
    "nav.about": "About",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.pricing": "Pricing",
    "nav.home": "Home",
    "nav.dental": "Dental",
    "nav.dentalCare": "Dental Care",
    "nav.dentalImplants": "Dental Implants",
    "nav.hollywoodSmile": "Hollywood Smile",
    "nav.fertility": "Fertility",
    "nav.cosmetic": "Cosmetic Surgery",
    "nav.hairTransplant": "Hair Transplant",
    "nav.bariatric": "Bariatric Surgery",
    "nav.eyeSurgery": "Eye Surgery",
    "nav.skinAesthetics": "Skin & Aesthetics",
    "nav.searchPlaceholder": "Search treatments...",
    "nav.getStarted": "Get Started",
    "nav.bookNow": "Book Now",
    "nav.learnMore": "Learn More",
    "nav.viewAll": "View All",
    "nav.readMore": "Read More",
    "nav.seeMore": "See More",
    "nav.backToTop": "Back to Top",
    "nav.menu": "Menu",
    "nav.close": "Close",
    "nav.language": "Language",
    "hero.title": "Save Up to 85%",
    "hero.subtitle": "on World-Class Medical Care",
    "hero.cta.primary": "Get Free Quote",
    "hero.cta.secondary": "View Treatments",
    "hero.trust": "JCI Accredited Hospitals",
    "hero.tagline": "Your Journey to Wellness Begins in Egypt",
    "hero.description": "Experience world-class medical care at a fraction of the cost. Our accredited hospitals and expert doctors deliver exceptional results.",
    "about.title": "About Sekhmet Wellness Journeys",
    "about.subtitle": "Your Trusted Partner in Medical Tourism",
    "about.mission.title": "Our Mission",
    "about.mission.text": "We connect international patients with Egypt's finest medical facilities, ensuring world-class healthcare at affordable prices with a seamless travel experience.",
    "about.vision.title": "Our Vision",
    "about.vision.text": "To make Egypt the leading destination for medical tourism, combining ancient healing traditions with cutting-edge modern medicine.",
    "about.whyUs.title": "Why Choose Us",
    "about.whyUs.subtitle": "What Sets Us Apart",
    "about.whyUs.accredited": "JCI Accredited Hospitals",
    "about.whyUs.accredited.desc": "All our partner hospitals meet the highest international standards for patient safety and care quality.",
    "about.whyUs.savings": "Up to 85% Savings",
    "about.whyUs.savings.desc": "Get world-class treatment at a fraction of the cost compared to the US, UK, and Europe.",
    "about.whyUs.doctors": "Expert Doctors",
    "about.whyUs.doctors.desc": "Our surgeons are internationally trained and certified with decades of experience.",
    "about.whyUs.support": "24/7 Patient Support",
    "about.whyUs.support.desc": "From your first inquiry to post-treatment follow-up, we're with you every step of the way.",
    "about.whyUs.travel": "Complete Travel Assistance",
    "about.whyUs.travel.desc": "We handle visa support, airport transfers, hotel bookings, and local transportation.",
    "about.whyUs.language": "Multilingual Team",
    "about.whyUs.language.desc": "Our team speaks English, Arabic, French, and more to ensure clear communication.",
    "about.story.title": "Our Story",
    "about.story.text": "Founded with a passion for connecting patients with exceptional medical care, Sekhmet Wellness Journeys was born from the belief that quality healthcare should be accessible to everyone.",
    "about.team.title": "Our Team",
    "about.team.subtitle": "Meet the Experts Behind Your Journey",
    "about.values.title": "Our Values",
    "about.values.quality": "Quality",
    "about.values.trust": "Trust",
    "about.values.care": "Care",
    "about.values.transparency": "Transparency",
    "treatments.title": "Our Treatments",
    "treatments.subtitle": "World-Class Medical Procedures in Egypt",
    "treatments.description": "Explore our comprehensive range of medical treatments, all performed by internationally certified doctors in JCI-accredited hospitals.",
    "treatments.dental.title": "Dental Treatments",
    "treatments.dental.desc": "Implants, veneers, Hollywood smile makeovers, and comprehensive dental care at world-class facilities.",
    "treatments.hair.title": "Hair Transplant",
    "treatments.hair.desc": "Advanced FUE and DHI hair restoration techniques with natural-looking results.",
    "treatments.cosmetic.title": "Cosmetic Surgery",
    "treatments.cosmetic.desc": "Rhinoplasty, facelifts, liposuction, tummy tucks, and body contouring by expert surgeons.",
    "treatments.eye.title": "Eye Surgery",
    "treatments.eye.desc": "LASIK, PRK, cataract surgery, and advanced vision correction procedures.",
    "treatments.bariatric.title": "Bariatric Surgery",
    "treatments.bariatric.desc": "Gastric sleeve, gastric bypass, and weight loss surgery with comprehensive aftercare.",
    "treatments.skin.title": "Skin & Aesthetics",
    "treatments.skin.desc": "Botox, fillers, chemical peels, laser treatments, and non-surgical rejuvenation.",
    "treatments.fertility.title": "Fertility Treatments",
    "treatments.fertility.desc": "IVF, IUI, egg freezing, and comprehensive reproductive medicine services.",
    "treatments.startingFrom": "Starting from",
    "treatments.getQuote": "Get Free Quote",
    "treatments.viewDetails": "View Details",
    "treatments.compareToUS": "compared to US prices",
    "treatments.savingsUpTo": "Save up to",
    "dentalCare.title": "Dental Care in Egypt",
    "dentalCare.subtitle": "World-Class Dental Treatments at Affordable Prices",
    "dentalCare.description": "From routine cleanings to advanced procedures, our dental experts provide comprehensive care using the latest technology.",
    "dentalCare.whyEgypt": "Why Choose Egypt for Dental Care?",
    "dentalCare.savings": "Save 75-88% compared to US & UK prices",
    "dentalCare.quality": "International quality standards and materials",
    "dentalCare.technology": "Latest dental technology and equipment",
    "dentalCare.experience": "Experienced, internationally trained dentists",
    "dentalCare.services": "Our Dental Services",
    "dentalCare.implants": "Dental Implants",
    "dentalCare.implants.desc": "Premium titanium implants with lifetime warranty, placed by expert implantologists.",
    "dentalCare.veneers": "Porcelain Veneers",
    "dentalCare.veneers.desc": "Custom-crafted veneers for a perfect, natural-looking smile transformation.",
    "dentalCare.crowns": "Crowns & Bridges",
    "dentalCare.crowns.desc": "Durable, aesthetic dental crowns and bridges using premium materials.",
    "dentalCare.whitening": "Teeth Whitening",
    "dentalCare.whitening.desc": "Professional in-office and take-home whitening treatments for a brighter smile.",
    "dentalCare.rootCanal": "Root Canal Treatment",
    "dentalCare.rootCanal.desc": "Pain-free root canal therapy using advanced rotary instruments.",
    "dentalCare.orthodontics": "Orthodontics",
    "dentalCare.orthodontics.desc": "Traditional braces and clear aligners for perfect tooth alignment.",
    "dentalImplants.title": "Dental Implants in Egypt",
    "dentalImplants.subtitle": "Premium Implants at 75-88% Less Than US Prices",
    "dentalImplants.description": "Get world-class dental implants from internationally certified implantologists using premium brands like Nobel Biocare, Straumann, and more.",
    "dentalImplants.benefits.title": "Why Dental Implants?",
    "dentalImplants.benefits.permanent": "Permanent Solution",
    "dentalImplants.benefits.natural": "Natural Look & Feel",
    "dentalImplants.benefits.bone": "Preserves Bone Health",
    "dentalImplants.benefits.function": "Full Chewing Function",
    "dentalImplants.process.title": "The Implant Process",
    "dentalImplants.process.consultation": "Free Consultation & 3D Scan",
    "dentalImplants.process.placement": "Implant Placement",
    "dentalImplants.process.healing": "Healing Period",
    "dentalImplants.process.crown": "Crown Attachment",
    "dentalImplants.pricing.title": "Implant Pricing",
    "dentalImplants.pricing.single": "Single Implant",
    "dentalImplants.pricing.allOn4": "All-on-4",
    "dentalImplants.pricing.allOn6": "All-on-6",
    "dentalImplants.pricing.fullMouth": "Full Mouth Restoration",
    "hollywoodSmile.title": "Hollywood Smile in Egypt",
    "hollywoodSmile.subtitle": "Transform Your Smile with World-Class Veneers",
    "hollywoodSmile.description": "Achieve the perfect celebrity smile with premium porcelain veneers crafted by Egypt's top cosmetic dentists.",
    "hollywoodSmile.whatIs": "What is a Hollywood Smile?",
    "hollywoodSmile.whatIs.desc": "A Hollywood Smile is a complete smile makeover using ultra-thin porcelain veneers to create a perfectly aligned, brilliantly white smile.",
    "hollywoodSmile.process.title": "Your Smile Journey",
    "hollywoodSmile.process.design": "Digital Smile Design",
    "hollywoodSmile.process.prep": "Tooth Preparation",
    "hollywoodSmile.process.temp": "Temporary Veneers",
    "hollywoodSmile.process.final": "Final Veneer Placement",
    "hollywoodSmile.benefits.title": "Benefits",
    "hollywoodSmile.benefits.instant": "Instant Transformation",
    "hollywoodSmile.benefits.durable": "10-15 Year Durability",
    "hollywoodSmile.benefits.stain": "Stain-Resistant",
    "hollywoodSmile.benefits.natural": "Natural Appearance",
    "fertility.title": "Fertility Treatments in Egypt",
    "fertility.subtitle": "Advanced Reproductive Medicine at Affordable Prices",
    "fertility.description": "Our fertility clinics offer comprehensive reproductive services including IVF, IUI, and egg freezing with high success rates.",
    "fertility.services.title": "Our Fertility Services",
    "fertility.ivf": "In Vitro Fertilization (IVF)",
    "fertility.ivf.desc": "Complete IVF cycles with advanced embryology labs and experienced specialists.",
    "fertility.iui": "Intrauterine Insemination (IUI)",
    "fertility.iui.desc": "Less invasive fertility treatment with carefully timed procedures.",
    "fertility.eggFreezing": "Egg Freezing",
    "fertility.eggFreezing.desc": "Preserve your fertility with our state-of-the-art vitrification technology.",
    "fertility.genetic": "Genetic Testing",
    "fertility.genetic.desc": "Pre-implantation genetic testing for healthier pregnancies.",
    "fertility.whyEgypt": "Why Choose Egypt for Fertility?",
    "fertility.successRates": "High Success Rates",
    "fertility.affordability": "60-70% More Affordable",
    "fertility.privacy": "Complete Privacy & Discretion",
    "fertility.technology": "Latest Technology",
    "howItWorks.title": "How It Works",
    "howItWorks.subtitle": "Your Journey in 4 Simple Steps",
    "howItWorks.description": "We make medical tourism simple, safe, and stress-free. Here's how your journey unfolds.",
    "howItWorks.step1.title": "Free Consultation",
    "howItWorks.step1.desc": "Share your medical needs and receive a personalized treatment plan with transparent pricing within 24 hours.",
    "howItWorks.step2.title": "Plan Your Trip",
    "howItWorks.step2.desc": "We arrange everything — flights, hotel, airport transfers, hospital appointments, and your treatment schedule.",
    "howItWorks.step3.title": "Receive Treatment",
    "howItWorks.step3.desc": "Get world-class treatment at a JCI-accredited hospital with your dedicated patient coordinator by your side.",
    "howItWorks.step4.title": "Recovery & Follow-Up",
    "howItWorks.step4.desc": "Recover comfortably with our aftercare support, and enjoy ongoing follow-up consultations once you're home.",
    "howItWorks.cta": "Start Your Journey Today",
    "howItWorks.guarantee.title": "Our Guarantee",
    "howItWorks.guarantee.desc": "We stand behind every treatment with our satisfaction guarantee and ongoing support.",
    "doctors.title": "Our Doctors",
    "doctors.subtitle": "Meet Egypt's Leading Medical Specialists",
    "doctors.description": "Our carefully selected team of doctors are internationally trained, board-certified, and bring decades of experience in their specialties.",
    "doctors.specialties": "Specialties",
    "doctors.experience": "Years of Experience",
    "doctors.education": "Education",
    "doctors.certifications": "Certifications",
    "doctors.languages": "Languages",
    "doctors.bookConsultation": "Book Consultation",
    "doctors.viewProfile": "View Profile",
    "doctors.qualifications": "Qualifications",
    "doctors.procedures": "Procedures Performed",
    "stories.title": "Patient Stories",
    "stories.subtitle": "Real Results from Real Patients",
    "stories.description": "Read about the experiences of patients who chose Egypt for their medical care and transformed their lives.",
    "stories.readStory": "Read Full Story",
    "stories.beforeAfter": "Before & After",
    "stories.treatment": "Treatment",
    "stories.country": "Country",
    "stories.savings": "Savings",
    "stories.rating": "Rating",
    "stories.verified": "Verified Patient",
    "stories.shareYourStory": "Share Your Story",
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Everything You Need to Know",
    "faq.description": "Get answers to the most common questions about medical tourism in Egypt.",
    "faq.categories.general": "General",
    "faq.categories.travel": "Travel & Logistics",
    "faq.categories.medical": "Medical",
    "faq.categories.pricing": "Pricing & Payment",
    "faq.categories.aftercare": "Aftercare",
    "faq.stillHaveQuestions": "Still Have Questions?",
    "faq.contactUs": "Contact us for personalized answers",
    "faq.q1": "Is medical treatment in Egypt safe?",
    "faq.a1": "Yes. Our partner hospitals are JCI-accredited, meeting the highest international standards for patient safety and care quality. Our doctors are internationally trained and board-certified.",
    "faq.q2": "How much can I save?",
    "faq.a2": "Patients typically save 50-85% compared to prices in the US, UK, and Europe, depending on the procedure.",
    "faq.q3": "What is included in the treatment package?",
    "faq.a3": "Our packages typically include the medical procedure, hospital stay, surgeon fees, medications, airport transfers, hotel accommodation, and a dedicated patient coordinator.",
    "faq.q4": "Do I need a visa to travel to Egypt?",
    "faq.a4": "Most nationalities can obtain a visa on arrival or an e-visa. We provide complete visa assistance as part of our service.",
    "faq.q5": "How long will I need to stay in Egypt?",
    "faq.a5": "The duration depends on your treatment. Most dental procedures require 5-7 days, while surgical procedures may require 7-14 days. We'll provide a detailed timeline during your consultation.",
    "faq.q6": "What happens if I have complications after returning home?",
    "faq.a6": "We provide comprehensive aftercare support including virtual follow-up consultations with your doctor, and can coordinate with local physicians in your home country if needed.",
    "travelGuide.title": "Egypt Travel Guide",
    "travelGuide.subtitle": "Everything You Need for Your Medical Trip",
    "travelGuide.description": "Plan your medical tourism trip to Egypt with our comprehensive guide covering visas, travel tips, accommodation, and more.",
    "travelGuide.visa.title": "Visa Information",
    "travelGuide.visa.desc": "Most nationalities can get a visa on arrival or e-visa. We provide complete visa assistance.",
    "travelGuide.flights.title": "Getting There",
    "travelGuide.flights.desc": "Cairo International Airport is well-connected with direct flights from major cities worldwide.",
    "travelGuide.accommodation.title": "Accommodation",
    "travelGuide.accommodation.desc": "From luxury 5-star hotels to comfortable recovery apartments near the hospital.",
    "travelGuide.weather.title": "Climate & Weather",
    "travelGuide.weather.desc": "Egypt enjoys warm weather year-round. Best times to visit are October to April.",
    "travelGuide.currency.title": "Currency & Payments",
    "travelGuide.currency.desc": "The Egyptian Pound (EGP) is the local currency. Major credit cards are widely accepted.",
    "travelGuide.safety.title": "Safety & Security",
    "travelGuide.safety.desc": "Egypt's medical tourism areas are safe and well-secured. We provide 24/7 support during your stay.",
    "travelGuide.culture.title": "Culture & Attractions",
    "travelGuide.culture.desc": "Combine your medical trip with visits to the Pyramids, Luxor, and other world-famous attractions.",
    "travelGuide.tips.title": "Travel Tips",
    "travelGuide.packing": "What to Pack",
    "travelGuide.transport": "Local Transportation",
    "travelGuide.food": "Food & Dining",
    "travelGuide.communication": "Communication",
    "pricing.title": "Treatment Pricing",
    "pricing.subtitle": "Transparent Pricing, No Hidden Fees",
    "pricing.description": "Compare our prices with US and UK costs. All prices include the procedure, hospital fees, and surgeon fees.",
    "pricing.procedure": "Procedure",
    "pricing.egyptPrice": "Egypt Price",
    "pricing.usPrice": "US Price",
    "pricing.ukPrice": "UK Price",
    "pricing.savings": "Savings",
    "pricing.allInclusive": "All-Inclusive Package",
    "pricing.includes": "What's Included",
    "pricing.getQuote": "Get Personalized Quote",
    "pricing.disclaimer": "Prices are approximate and may vary based on individual needs. Final pricing provided after consultation.",
    "pricing.viewAll": "View All Prices",
    "pricing.compareAndSave": "Compare & Save",
    "pricing.categories.dental": "Dental",
    "pricing.categories.hair": "Hair Transplant",
    "pricing.categories.cosmetic": "Cosmetic Surgery",
    "pricing.categories.eye": "Eye Surgery",
    "pricing.categories.bariatric": "Bariatric Surgery",
    "pricing.categories.skin": "Skin & Aesthetics",
    "consultation.title": "Free Consultation",
    "consultation.subtitle": "Get Your Personalized Treatment Plan",
    "consultation.description": "Fill out the form below and our medical team will review your case and provide a detailed treatment plan with pricing within 24 hours.",
    "consultation.form.name": "Full Name",
    "consultation.form.email": "Email Address",
    "consultation.form.phone": "Phone Number",
    "consultation.form.country": "Country",
    "consultation.form.treatment": "Treatment Interest",
    "consultation.form.message": "Tell us about your medical needs",
    "consultation.form.submit": "Submit Consultation Request",
    "consultation.form.uploading": "Upload Medical Records (Optional)",
    "consultation.form.privacy": "Your information is confidential and protected.",
    "consultation.benefits.title": "What You'll Receive",
    "consultation.benefits.plan": "Personalized Treatment Plan",
    "consultation.benefits.pricing": "Detailed Cost Breakdown",
    "consultation.benefits.timeline": "Treatment Timeline",
    "consultation.benefits.doctor": "Doctor Recommendations",
    "consultation.response": "We typically respond within 24 hours",
    "contact.title": "Contact Us",
    "contact.subtitle": "We're Here to Help",
    "contact.description": "Have questions? Reach out to us through any of the channels below.",
    "contact.form.name": "Your Name",
    "contact.form.email": "Your Email",
    "contact.form.subject": "Subject",
    "contact.form.message": "Your Message",
    "contact.form.send": "Send Message",
    "contact.info.phone": "Phone",
    "contact.info.email": "Email",
    "contact.info.address": "Address",
    "contact.info.hours": "Working Hours",
    "contact.info.whatsapp": "WhatsApp",
    "contact.followUs": "Follow Us",
    "blog.title": "Blog",
    "blog.subtitle": "Medical Tourism Insights & Tips",
    "blog.description": "Stay informed with the latest news, tips, and insights about medical tourism in Egypt.",
    "blog.readTime": "min read",
    "blog.category": "Category",
    "blog.recentPosts": "Recent Posts",
    "blog.allPosts": "All Posts",
    "blog.searchPosts": "Search posts...",
    "blog.noResults": "No posts found",
    "blog.backToBlog": "Back to Blog",
    "footer.description": "Your trusted partner for world-class medical care in Egypt. Save up to 85% on treatments at JCI-accredited hospitals.",
    "footer.quickLinks": "Quick Links",
    "footer.treatments": "Treatments",
    "footer.aboutUs": "About Us",
    "footer.contactUs": "Contact Us",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.disclaimer": "Medical Disclaimer",
    "footer.connect": "Connect",
    "footer.newsletter": "Newsletter",
    "footer.newsletter.placeholder": "Enter your email",
    "footer.newsletter.subscribe": "Subscribe",
    "footer.newsletter.desc": "Get the latest updates on treatments and special offers.",
    "footer.copyright": "© 2026 Sekhmet Wellness Journeys. All rights reserved.",
    "footer.accredited": "JCI Accredited Partner",
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.tryAgain": "Try Again",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.submit": "Submit",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.yes": "Yes",
    "common.no": "No",
    "common.or": "or",
    "common.and": "and",
    "common.free": "Free",
    "common.from": "From",
    "common.perMonth": "per month",
    "common.patients": "Patients",
    "common.reviews": "Reviews",
    "common.stars": "Stars",
    "common.viewMore": "View More",
    "common.callNow": "Call Now",
    "common.whatsapp": "WhatsApp Us",
    "common.email": "Email Us",
    "common.phone": "Phone",
    "common.address": "Address",
    "trust.jciAccredited": "JCI Accredited",
    "trust.patientsServed": "Patients Served",
    "trust.successRate": "Success Rate",
    "trust.yearsExperience": "Years Experience",
    "trust.countriesServed": "Countries Served",
    "trust.satisfaction": "Patient Satisfaction",
    "trust.support247": "24/7 Support",
    "trust.moneyBack": "Satisfaction Guarantee",
    "trust.freeConsultation": "Free Consultation",
    "trust.noHiddenFees": "No Hidden Fees",
    "cta.readyToStart": "Ready to Start Your Journey?",
    "cta.getStartedToday": "Get Started Today",
    "cta.freeQuote": "Get Your Free Quote",
    "cta.scheduleCall": "Schedule a Call",
    "cta.talkToExpert": "Talk to an Expert",
    "cta.startSaving": "Start Saving Today",
    "cta.compareAndSave": "Compare & Save",
    "cta.bookConsultation": "Book Free Consultation",
    "cta.noObligation": "No obligation. 100% free.",
    "cta.responseTime": "Response within 24 hours",
    "calculator.title": "Cost Calculator",
    "calculator.subtitle": "Estimate Your Savings",
    "calculator.selectTreatment": "Select Treatment",
    "calculator.yourCountry": "Your Country",
    "calculator.estimatedCost": "Estimated Cost in Egypt",
    "calculator.typicalCost": "Typical Cost in Your Country",
    "calculator.youSave": "You Save",
    "calculator.includes": "Price Includes",
    "calculator.note": "Final price determined after consultation",
    "specialties.title": "Our Specialties",
    "specialties.subtitle": "Comprehensive Medical Care",
    "specialties.explore": "Explore"
  },
  "ar": {
    "nav.treatments": "العلاجات",
    "nav.howItWorks": "كيف نعمل",
    "nav.doctors": "الأطباء",
    "nav.stories": "قصص النجاح",
    "nav.travelGuide": "دليل السفر",
    "nav.faq": "الأسئلة الشائعة",
    "nav.freeConsultation": "استشارة مجانية",
    "nav.about": "من نحن",
    "nav.blog": "المدونة",
    "nav.contact": "اتصل بنا",
    "nav.pricing": "الأسعار",
    "nav.home": "الرئيسية",
    "nav.dental": "طب الأسنان",
    "nav.dentalCare": "العناية بالأسنان",
    "nav.dentalImplants": "زراعة الأسنان",
    "nav.hollywoodSmile": "ابتسامة هوليوود",
    "nav.fertility": "علاج الخصوبة",
    "nav.cosmetic": "الجراحة التجميلية",
    "nav.hairTransplant": "زراعة الشعر",
    "nav.bariatric": "جراحة السمنة",
    "nav.eyeSurgery": "جراحة العيون",
    "nav.skinAesthetics": "البشرة والتجميل",
    "nav.searchPlaceholder": "ابحث عن العلاجات...",
    "nav.getStarted": "ابدأ الآن",
    "nav.bookNow": "احجز الآن",
    "nav.learnMore": "اعرف المزيد",
    "nav.viewAll": "عرض الكل",
    "nav.readMore": "اقرأ المزيد",
    "nav.seeMore": "شاهد المزيد",
    "nav.backToTop": "العودة للأعلى",
    "nav.menu": "القائمة",
    "nav.close": "إغلاق",
    "nav.language": "اللغة",
    "hero.title": "وفّر حتى 85%",
    "hero.subtitle": "على رعاية طبية عالمية",
    "hero.cta.primary": "احصل على عرض سعر",
    "hero.cta.secondary": "عرض العلاجات",
    "hero.trust": "مستشفيات معتمدة دولياً",
    "hero.tagline": "رحلتك نحو العافية تبدأ من مصر",
    "hero.description": "اختبر رعاية طبية عالمية بجزء بسيط من التكلفة. مستشفياتنا المعتمدة وأطباؤنا الخبراء يقدمون نتائج استثنائية.",
    "about.title": "عن سخمت لرحلات العافية",
    "about.subtitle": "شريكك الموثوق في السياحة العلاجية",
    "about.mission.title": "مهمتنا",
    "about.mission.text": "نربط المرضى الدوليين بأفضل المرافق الطبية في مصر، مع ضمان رعاية صحية عالمية بأسعار معقولة وتجربة سفر سلسة.",
    "about.vision.title": "رؤيتنا",
    "about.vision.text": "جعل مصر الوجهة الرائدة في السياحة العلاجية، من خلال الجمع بين تقاليد الشفاء القديمة والطب الحديث المتطور.",
    "about.whyUs.title": "لماذا تختارنا",
    "about.whyUs.subtitle": "ما يميزنا",
    "about.whyUs.accredited": "مستشفيات معتمدة دولياً",
    "about.whyUs.accredited.desc": "جميع مستشفياتنا الشريكة تستوفي أعلى المعايير الدولية لسلامة المرضى وجودة الرعاية.",
    "about.whyUs.savings": "توفير حتى 85%",
    "about.whyUs.savings.desc": "احصل على علاج عالمي بجزء بسيط من التكلفة مقارنة بأمريكا وبريطانيا وأوروبا.",
    "about.whyUs.doctors": "أطباء خبراء",
    "about.whyUs.doctors.desc": "جراحونا مدربون ومعتمدون دولياً مع عقود من الخبرة.",
    "about.whyUs.support": "دعم على مدار الساعة",
    "about.whyUs.support.desc": "من أول استفسار حتى المتابعة بعد العلاج، نحن معك في كل خطوة.",
    "about.whyUs.travel": "مساعدة سفر كاملة",
    "about.whyUs.travel.desc": "نتولى دعم التأشيرة والنقل من المطار وحجز الفنادق والمواصلات المحلية.",
    "about.whyUs.language": "فريق متعدد اللغات",
    "about.whyUs.language.desc": "فريقنا يتحدث العربية والإنجليزية والفرنسية وغيرها لضمان تواصل واضح.",
    "about.story.title": "قصتنا",
    "about.story.text": "تأسست سخمت لرحلات العافية من إيمان بأن الرعاية الصحية عالية الجودة يجب أن تكون في متناول الجميع.",
    "about.team.title": "فريقنا",
    "about.team.subtitle": "تعرف على الخبراء وراء رحلتك",
    "about.values.title": "قيمنا",
    "about.values.quality": "الجودة",
    "about.values.trust": "الثقة",
    "about.values.care": "الرعاية",
    "about.values.transparency": "الشفافية",
    "treatments.title": "علاجاتنا",
    "treatments.subtitle": "إجراءات طبية عالمية في مصر",
    "treatments.description": "استكشف مجموعتنا الشاملة من العلاجات الطبية، جميعها يقوم بها أطباء معتمدون دولياً في مستشفيات معتمدة.",
    "treatments.dental.title": "علاجات الأسنان",
    "treatments.dental.desc": "زراعة أسنان وقشور وابتسامة هوليوود ورعاية شاملة للأسنان في مرافق عالمية.",
    "treatments.hair.title": "زراعة الشعر",
    "treatments.hair.desc": "تقنيات متقدمة لاستعادة الشعر بتقنية FUE و DHI مع نتائج طبيعية.",
    "treatments.cosmetic.title": "الجراحة التجميلية",
    "treatments.cosmetic.desc": "تجميل الأنف وشد الوجه وشفط الدهون وشد البطن ونحت الجسم على يد جراحين خبراء.",
    "treatments.eye.title": "جراحة العيون",
    "treatments.eye.desc": "الليزك و PRK وجراحة الساد وإجراءات تصحيح النظر المتقدمة.",
    "treatments.bariatric.title": "جراحة السمنة",
    "treatments.bariatric.desc": "تكميم المعدة وتحويل المسار وجراحة فقدان الوزن مع رعاية شاملة بعد العملية.",
    "treatments.skin.title": "البشرة والتجميل",
    "treatments.skin.desc": "البوتوكس والفيلر والتقشير الكيميائي والعلاج بالليزر والتجديد غير الجراحي.",
    "treatments.fertility.title": "علاجات الخصوبة",
    "treatments.fertility.desc": "التلقيح الصناعي والتلقيح داخل الرحم وتجميد البويضات وخدمات الطب التناسلي الشاملة.",
    "treatments.startingFrom": "تبدأ من",
    "treatments.getQuote": "احصل على عرض سعر مجاني",
    "treatments.viewDetails": "عرض التفاصيل",
    "treatments.compareToUS": "مقارنة بالأسعار الأمريكية",
    "treatments.savingsUpTo": "وفّر حتى",
    "dentalCare.title": "العناية بالأسنان في مصر",
    "dentalCare.subtitle": "علاجات أسنان عالمية بأسعار معقولة",
    "dentalCare.description": "من التنظيف الروتيني إلى الإجراءات المتقدمة، يقدم خبراء الأسنان لدينا رعاية شاملة باستخدام أحدث التقنيات.",
    "dentalCare.whyEgypt": "لماذا تختار مصر لعلاج الأسنان؟",
    "dentalCare.savings": "وفّر 75-88% مقارنة بأسعار أمريكا وبريطانيا",
    "dentalCare.quality": "معايير ومواد جودة دولية",
    "dentalCare.technology": "أحدث تقنيات ومعدات طب الأسنان",
    "dentalCare.experience": "أطباء أسنان ذوو خبرة ومدربون دولياً",
    "dentalCare.services": "خدمات الأسنان لدينا",
    "dentalCare.implants": "زراعة الأسنان",
    "dentalCare.implants.desc": "زرعات تيتانيوم ممتازة مع ضمان مدى الحياة، يزرعها أخصائيون خبراء.",
    "dentalCare.veneers": "قشور البورسلين",
    "dentalCare.veneers.desc": "قشور مصنوعة خصيصاً لتحويل ابتسامتك بمظهر طبيعي مثالي.",
    "dentalCare.crowns": "التيجان والجسور",
    "dentalCare.crowns.desc": "تيجان وجسور أسنان متينة وجمالية باستخدام مواد ممتازة.",
    "dentalCare.whitening": "تبييض الأسنان",
    "dentalCare.whitening.desc": "علاجات تبييض احترافية في العيادة وللاستخدام المنزلي لابتسامة أكثر إشراقاً.",
    "dentalCare.rootCanal": "علاج قناة الجذر",
    "dentalCare.rootCanal.desc": "علاج قناة الجذر بدون ألم باستخدام أدوات دوارة متقدمة.",
    "dentalCare.orthodontics": "تقويم الأسنان",
    "dentalCare.orthodontics.desc": "تقويم تقليدي ومقوّمات شفافة لمحاذاة الأسنان المثالية.",
    "dentalImplants.title": "زراعة الأسنان في مصر",
    "dentalImplants.subtitle": "زرعات ممتازة بأقل من 75-88% من الأسعار الأمريكية",
    "dentalImplants.description": "احصل على زراعة أسنان عالمية من أخصائيين معتمدين دولياً باستخدام أفضل العلامات التجارية مثل نوبل بيوكير وستروومان.",
    "dentalImplants.benefits.title": "لماذا زراعة الأسنان؟",
    "dentalImplants.benefits.permanent": "حل دائم",
    "dentalImplants.benefits.natural": "مظهر وإحساس طبيعي",
    "dentalImplants.benefits.bone": "يحافظ على صحة العظام",
    "dentalImplants.benefits.function": "وظيفة مضغ كاملة",
    "dentalImplants.process.title": "مراحل الزراعة",
    "dentalImplants.process.consultation": "استشارة مجانية ومسح ثلاثي الأبعاد",
    "dentalImplants.process.placement": "وضع الزرعة",
    "dentalImplants.process.healing": "فترة الشفاء",
    "dentalImplants.process.crown": "تركيب التاج",
    "dentalImplants.pricing.title": "أسعار الزراعة",
    "dentalImplants.pricing.single": "زرعة واحدة",
    "dentalImplants.pricing.allOn4": "الكل على 4",
    "dentalImplants.pricing.allOn6": "الكل على 6",
    "dentalImplants.pricing.fullMouth": "ترميم الفم الكامل",
    "hollywoodSmile.title": "ابتسامة هوليوود في مصر",
    "hollywoodSmile.subtitle": "حوّل ابتسامتك مع قشور عالمية",
    "hollywoodSmile.description": "احصل على ابتسامة المشاهير المثالية مع قشور بورسلين ممتازة من أفضل أطباء الأسنان التجميليين في مصر.",
    "hollywoodSmile.whatIs": "ما هي ابتسامة هوليوود؟",
    "hollywoodSmile.whatIs.desc": "ابتسامة هوليوود هي تحول كامل للابتسامة باستخدام قشور بورسلين رقيقة جداً لإنشاء ابتسامة متناسقة ومشرقة بشكل مثالي.",
    "hollywoodSmile.process.title": "رحلة ابتسامتك",
    "hollywoodSmile.process.design": "تصميم الابتسامة الرقمي",
    "hollywoodSmile.process.prep": "تحضير الأسنان",
    "hollywoodSmile.process.temp": "قشور مؤقتة",
    "hollywoodSmile.process.final": "تركيب القشور النهائية",
    "hollywoodSmile.benefits.title": "المزايا",
    "hollywoodSmile.benefits.instant": "تحول فوري",
    "hollywoodSmile.benefits.durable": "متانة 10-15 سنة",
    "hollywoodSmile.benefits.stain": "مقاومة للبقع",
    "hollywoodSmile.benefits.natural": "مظهر طبيعي",
    "fertility.title": "علاجات الخصوبة في مصر",
    "fertility.subtitle": "طب تناسلي متقدم بأسعار معقولة",
    "fertility.description": "تقدم عيادات الخصوبة لدينا خدمات تناسلية شاملة تشمل التلقيح الصناعي والتلقيح داخل الرحم وتجميد البويضات بمعدلات نجاح عالية.",
    "fertility.services.title": "خدمات الخصوبة لدينا",
    "fertility.ivf": "التلقيح الصناعي (أطفال الأنابيب)",
    "fertility.ivf.desc": "دورات تلقيح صناعي كاملة مع مختبرات أجنة متقدمة وأخصائيين ذوي خبرة.",
    "fertility.iui": "التلقيح داخل الرحم",
    "fertility.iui.desc": "علاج خصوبة أقل تدخلاً مع إجراءات محددة التوقيت بدقة.",
    "fertility.eggFreezing": "تجميد البويضات",
    "fertility.eggFreezing.desc": "احفظي خصوبتك مع تقنية التزجيج المتطورة لدينا.",
    "fertility.genetic": "الفحص الجيني",
    "fertility.genetic.desc": "فحص جيني قبل الزرع لحمل أكثر صحة.",
    "fertility.whyEgypt": "لماذا تختار مصر للخصوبة؟",
    "fertility.successRates": "معدلات نجاح عالية",
    "fertility.affordability": "أقل تكلفة بنسبة 60-70%",
    "fertility.privacy": "خصوصية وتكتم تام",
    "fertility.technology": "أحدث التقنيات",
    "howItWorks.title": "كيف نعمل",
    "howItWorks.subtitle": "رحلتك في 4 خطوات بسيطة",
    "howItWorks.description": "نجعل السياحة العلاجية بسيطة وآمنة وخالية من التوتر. إليك كيف تسير رحلتك.",
    "howItWorks.step1.title": "استشارة مجانية",
    "howItWorks.step1.desc": "شارك احتياجاتك الطبية واحصل على خطة علاج شخصية مع أسعار شفافة خلال 24 ساعة.",
    "howItWorks.step2.title": "خطط لرحلتك",
    "howItWorks.step2.desc": "نرتب كل شيء — الرحلات والفندق والنقل من المطار ومواعيد المستشفى وجدول علاجك.",
    "howItWorks.step3.title": "تلقّ العلاج",
    "howItWorks.step3.desc": "احصل على علاج عالمي في مستشفى معتمد دولياً مع منسق مريض مخصص بجانبك.",
    "howItWorks.step4.title": "التعافي والمتابعة",
    "howItWorks.step4.desc": "تعافَ براحة مع دعم الرعاية اللاحقة، واستمتع بمتابعة مستمرة بعد عودتك للوطن.",
    "howItWorks.cta": "ابدأ رحلتك اليوم",
    "howItWorks.guarantee.title": "ضمانتنا",
    "howItWorks.guarantee.desc": "نقف وراء كل علاج مع ضمان الرضا والدعم المستمر.",
    "doctors.title": "أطباؤنا",
    "doctors.subtitle": "تعرف على أبرز الأطباء المتخصصين في مصر",
    "doctors.description": "فريق أطبائنا المختارين بعناية مدربون دولياً ومعتمدون ويمتلكون عقوداً من الخبرة في تخصصاتهم.",
    "doctors.specialties": "التخصصات",
    "doctors.experience": "سنوات الخبرة",
    "doctors.education": "التعليم",
    "doctors.certifications": "الشهادات",
    "doctors.languages": "اللغات",
    "doctors.bookConsultation": "احجز استشارة",
    "doctors.viewProfile": "عرض الملف الشخصي",
    "doctors.qualifications": "المؤهلات",
    "doctors.procedures": "العمليات المنجزة",
    "stories.title": "قصص المرضى",
    "stories.subtitle": "نتائج حقيقية من مرضى حقيقيين",
    "stories.description": "اقرأ عن تجارب المرضى الذين اختاروا مصر لرعايتهم الطبية وغيّروا حياتهم.",
    "stories.readStory": "اقرأ القصة الكاملة",
    "stories.beforeAfter": "قبل وبعد",
    "stories.treatment": "العلاج",
    "stories.country": "البلد",
    "stories.savings": "التوفير",
    "stories.rating": "التقييم",
    "stories.verified": "مريض موثق",
    "stories.shareYourStory": "شارك قصتك",
    "faq.title": "الأسئلة الشائعة",
    "faq.subtitle": "كل ما تحتاج معرفته",
    "faq.description": "احصل على إجابات لأكثر الأسئلة شيوعاً حول السياحة العلاجية في مصر.",
    "faq.categories.general": "عام",
    "faq.categories.travel": "السفر والخدمات اللوجستية",
    "faq.categories.medical": "طبي",
    "faq.categories.pricing": "الأسعار والدفع",
    "faq.categories.aftercare": "الرعاية اللاحقة",
    "faq.stillHaveQuestions": "لا تزال لديك أسئلة؟",
    "faq.contactUs": "تواصل معنا للحصول على إجابات مخصصة",
    "faq.q1": "هل العلاج الطبي في مصر آمن؟",
    "faq.a1": "نعم. مستشفياتنا الشريكة معتمدة دولياً وتستوفي أعلى المعايير الدولية لسلامة المرضى وجودة الرعاية. أطباؤنا مدربون دولياً ومعتمدون.",
    "faq.q2": "كم يمكنني أن أوفر؟",
    "faq.a2": "يوفر المرضى عادة 50-85% مقارنة بالأسعار في أمريكا وبريطانيا وأوروبا، حسب الإجراء.",
    "faq.q3": "ما المشمول في حزمة العلاج؟",
    "faq.a3": "تشمل حزمنا عادة الإجراء الطبي والإقامة في المستشفى وأتعاب الجراح والأدوية والنقل من المطار وإقامة الفندق ومنسق مريض مخصص.",
    "faq.q4": "هل أحتاج تأشيرة للسفر إلى مصر؟",
    "faq.a4": "معظم الجنسيات يمكنها الحصول على تأشيرة عند الوصول أو تأشيرة إلكترونية. نقدم مساعدة كاملة للتأشيرة كجزء من خدمتنا.",
    "faq.q5": "كم من الوقت سأحتاج للبقاء في مصر؟",
    "faq.a5": "تعتمد المدة على علاجك. معظم إجراءات الأسنان تتطلب 5-7 أيام، بينما الإجراءات الجراحية قد تتطلب 7-14 يوماً. سنقدم جدولاً زمنياً مفصلاً خلال استشارتك.",
    "faq.q6": "ماذا يحدث إذا حدثت مضاعفات بعد العودة للوطن؟",
    "faq.a6": "نقدم دعم رعاية لاحقة شامل بما في ذلك استشارات متابعة افتراضية مع طبيبك، ويمكننا التنسيق مع أطباء محليين في بلدك إذا لزم الأمر.",
    "travelGuide.title": "دليل السفر إلى مصر",
    "travelGuide.subtitle": "كل ما تحتاجه لرحلتك العلاجية",
    "travelGuide.description": "خطط لرحلة السياحة العلاجية إلى مصر مع دليلنا الشامل الذي يغطي التأشيرات ونصائح السفر والإقامة والمزيد.",
    "travelGuide.visa.title": "معلومات التأشيرة",
    "travelGuide.visa.desc": "معظم الجنسيات يمكنها الحصول على تأشيرة عند الوصول أو تأشيرة إلكترونية. نقدم مساعدة كاملة للتأشيرة.",
    "travelGuide.flights.title": "الوصول",
    "travelGuide.flights.desc": "مطار القاهرة الدولي متصل جيداً مع رحلات مباشرة من المدن الرئيسية حول العالم.",
    "travelGuide.accommodation.title": "الإقامة",
    "travelGuide.accommodation.desc": "من فنادق فاخرة 5 نجوم إلى شقق تعافي مريحة بالقرب من المستشفى.",
    "travelGuide.weather.title": "المناخ والطقس",
    "travelGuide.weather.desc": "تتمتع مصر بطقس دافئ على مدار السنة. أفضل أوقات الزيارة من أكتوبر إلى أبريل.",
    "travelGuide.currency.title": "العملة والمدفوعات",
    "travelGuide.currency.desc": "الجنيه المصري هو العملة المحلية. بطاقات الائتمان الرئيسية مقبولة على نطاق واسع.",
    "travelGuide.safety.title": "الأمان والأمن",
    "travelGuide.safety.desc": "مناطق السياحة العلاجية في مصر آمنة ومؤمنة جيداً. نقدم دعم على مدار الساعة خلال إقامتك.",
    "travelGuide.culture.title": "الثقافة والمعالم",
    "travelGuide.culture.desc": "اجمع رحلتك العلاجية مع زيارات للأهرامات والأقصر ومعالم مصر الشهيرة عالمياً.",
    "travelGuide.tips.title": "نصائح السفر",
    "travelGuide.packing": "ما تحتاج لحزمه",
    "travelGuide.transport": "المواصلات المحلية",
    "travelGuide.food": "الطعام والمطاعم",
    "travelGuide.communication": "التواصل",
    "pricing.title": "أسعار العلاجات",
    "pricing.subtitle": "أسعار شفافة بدون رسوم خفية",
    "pricing.description": "قارن أسعارنا مع تكاليف أمريكا وبريطانيا. جميع الأسعار تشمل الإجراء ورسوم المستشفى وأتعاب الجراح.",
    "pricing.procedure": "الإجراء",
    "pricing.egyptPrice": "السعر في مصر",
    "pricing.usPrice": "السعر في أمريكا",
    "pricing.ukPrice": "السعر في بريطانيا",
    "pricing.savings": "التوفير",
    "pricing.allInclusive": "الحزمة الشاملة",
    "pricing.includes": "ما المشمول",
    "pricing.getQuote": "احصل على عرض سعر مخصص",
    "pricing.disclaimer": "الأسعار تقريبية وقد تختلف حسب الاحتياجات الفردية. السعر النهائي يُقدم بعد الاستشارة.",
    "pricing.viewAll": "عرض جميع الأسعار",
    "pricing.compareAndSave": "قارن ووفّر",
    "pricing.categories.dental": "الأسنان",
    "pricing.categories.hair": "زراعة الشعر",
    "pricing.categories.cosmetic": "الجراحة التجميلية",
    "pricing.categories.eye": "جراحة العيون",
    "pricing.categories.bariatric": "جراحة السمنة",
    "pricing.categories.skin": "البشرة والتجميل",
    "consultation.title": "استشارة مجانية",
    "consultation.subtitle": "احصل على خطة علاجك المخصصة",
    "consultation.description": "املأ النموذج أدناه وسيراجع فريقنا الطبي حالتك ويقدم خطة علاج مفصلة مع الأسعار خلال 24 ساعة.",
    "consultation.form.name": "الاسم الكامل",
    "consultation.form.email": "البريد الإلكتروني",
    "consultation.form.phone": "رقم الهاتف",
    "consultation.form.country": "البلد",
    "consultation.form.treatment": "العلاج المطلوب",
    "consultation.form.message": "أخبرنا عن احتياجاتك الطبية",
    "consultation.form.submit": "إرسال طلب الاستشارة",
    "consultation.form.uploading": "رفع السجلات الطبية (اختياري)",
    "consultation.form.privacy": "معلوماتك سرية ومحمية.",
    "consultation.benefits.title": "ماذا ستتلقى",
    "consultation.benefits.plan": "خطة علاج مخصصة",
    "consultation.benefits.pricing": "تفصيل مفصل للتكاليف",
    "consultation.benefits.timeline": "جدول زمني للعلاج",
    "consultation.benefits.doctor": "توصيات الأطباء",
    "consultation.response": "نرد عادة خلال 24 ساعة",
    "contact.title": "اتصل بنا",
    "contact.subtitle": "نحن هنا للمساعدة",
    "contact.description": "لديك أسئلة؟ تواصل معنا عبر أي من القنوات أدناه.",
    "contact.form.name": "اسمك",
    "contact.form.email": "بريدك الإلكتروني",
    "contact.form.subject": "الموضوع",
    "contact.form.message": "رسالتك",
    "contact.form.send": "إرسال الرسالة",
    "contact.info.phone": "الهاتف",
    "contact.info.email": "البريد الإلكتروني",
    "contact.info.address": "العنوان",
    "contact.info.hours": "ساعات العمل",
    "contact.info.whatsapp": "واتساب",
    "contact.followUs": "تابعنا",
    "blog.title": "المدونة",
    "blog.subtitle": "رؤى ونصائح السياحة العلاجية",
    "blog.description": "ابقَ على اطلاع بأحدث الأخبار والنصائح والرؤى حول السياحة العلاجية في مصر.",
    "blog.readTime": "دقيقة قراءة",
    "blog.category": "الفئة",
    "blog.recentPosts": "أحدث المقالات",
    "blog.allPosts": "جميع المقالات",
    "blog.searchPosts": "ابحث في المقالات...",
    "blog.noResults": "لم يتم العثور على مقالات",
    "blog.backToBlog": "العودة للمدونة",
    "footer.description": "شريكك الموثوق للرعاية الطبية العالمية في مصر. وفّر حتى 85% على العلاجات في مستشفيات معتمدة دولياً.",
    "footer.quickLinks": "روابط سريعة",
    "footer.treatments": "العلاجات",
    "footer.aboutUs": "من نحن",
    "footer.contactUs": "اتصل بنا",
    "footer.legal": "قانوني",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.disclaimer": "إخلاء المسؤولية الطبية",
    "footer.connect": "تواصل",
    "footer.newsletter": "النشرة الإخبارية",
    "footer.newsletter.placeholder": "أدخل بريدك الإلكتروني",
    "footer.newsletter.subscribe": "اشترك",
    "footer.newsletter.desc": "احصل على أحدث التحديثات حول العلاجات والعروض الخاصة.",
    "footer.copyright": "© 2026 سخمت لرحلات العافية. جميع الحقوق محفوظة.",
    "footer.accredited": "شريك معتمد دولياً",
    "common.loading": "جاري التحميل...",
    "common.error": "حدث خطأ ما",
    "common.tryAgain": "حاول مرة أخرى",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.previous": "السابق",
    "common.submit": "إرسال",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.or": "أو",
    "common.and": "و",
    "common.free": "مجاني",
    "common.from": "من",
    "common.perMonth": "شهرياً",
    "common.patients": "مرضى",
    "common.reviews": "تقييمات",
    "common.stars": "نجوم",
    "common.viewMore": "عرض المزيد",
    "common.callNow": "اتصل الآن",
    "common.whatsapp": "راسلنا عبر واتساب",
    "common.email": "راسلنا",
    "common.phone": "الهاتف",
    "common.address": "العنوان",
    "trust.jciAccredited": "معتمد دولياً",
    "trust.patientsServed": "مرضى تمت خدمتهم",
    "trust.successRate": "معدل النجاح",
    "trust.yearsExperience": "سنوات الخبرة",
    "trust.countriesServed": "دولة تمت خدمتها",
    "trust.satisfaction": "رضا المرضى",
    "trust.support247": "دعم على مدار الساعة",
    "trust.moneyBack": "ضمان الرضا",
    "trust.freeConsultation": "استشارة مجانية",
    "trust.noHiddenFees": "بدون رسوم خفية",
    "cta.readyToStart": "مستعد لبدء رحلتك؟",
    "cta.getStartedToday": "ابدأ اليوم",
    "cta.freeQuote": "احصل على عرض سعر مجاني",
    "cta.scheduleCall": "جدولة مكالمة",
    "cta.talkToExpert": "تحدث مع خبير",
    "cta.startSaving": "ابدأ التوفير اليوم",
    "cta.compareAndSave": "قارن ووفّر",
    "cta.bookConsultation": "احجز استشارة مجانية",
    "cta.noObligation": "بدون التزام. مجاني 100%.",
    "cta.responseTime": "الرد خلال 24 ساعة",
    "calculator.title": "حاسبة التكلفة",
    "calculator.subtitle": "قدّر مدخراتك",
    "calculator.selectTreatment": "اختر العلاج",
    "calculator.yourCountry": "بلدك",
    "calculator.estimatedCost": "التكلفة التقديرية في مصر",
    "calculator.typicalCost": "التكلفة المعتادة في بلدك",
    "calculator.youSave": "ستوفر",
    "calculator.includes": "السعر يشمل",
    "calculator.note": "السعر النهائي يُحدد بعد الاستشارة",
    "specialties.title": "تخصصاتنا",
    "specialties.subtitle": "رعاية طبية شاملة",
    "specialties.explore": "استكشف"
  },
  "fr": {
    "nav.treatments": "Traitements",
    "nav.howItWorks": "Comment ça marche",
    "nav.doctors": "Médecins",
    "nav.stories": "Témoignages",
    "nav.travelGuide": "Guide de Voyage",
    "nav.faq": "FAQ",
    "nav.freeConsultation": "Consultation Gratuite",
    "nav.about": "À Propos",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.pricing": "Tarifs",
    "nav.home": "Accueil",
    "nav.dental": "Dentaire",
    "nav.dentalCare": "Soins Dentaires",
    "nav.dentalImplants": "Implants Dentaires",
    "nav.hollywoodSmile": "Sourire Hollywood",
    "nav.fertility": "Fertilité",
    "nav.cosmetic": "Chirurgie Esthétique",
    "nav.hairTransplant": "Greffe de Cheveux",
    "nav.bariatric": "Chirurgie Bariatrique",
    "nav.eyeSurgery": "Chirurgie des Yeux",
    "nav.skinAesthetics": "Peau & Esthétique",
    "nav.searchPlaceholder": "Rechercher des traitements...",
    "nav.getStarted": "Commencer",
    "nav.bookNow": "Réserver",
    "nav.learnMore": "En Savoir Plus",
    "nav.viewAll": "Voir Tout",
    "nav.readMore": "Lire la Suite",
    "nav.seeMore": "Voir Plus",
    "nav.backToTop": "Retour en Haut",
    "nav.menu": "Menu",
    "nav.close": "Fermer",
    "nav.language": "Langue",
    "hero.title": "Économisez jusqu'à 85%",
    "hero.subtitle": "sur des soins médicaux de classe mondiale",
    "hero.cta.primary": "Devis Gratuit",
    "hero.cta.secondary": "Voir les Traitements",
    "hero.trust": "Hôpitaux Accrédités JCI",
    "hero.tagline": "Votre Voyage vers le Bien-être Commence en Égypte",
    "hero.description": "Découvrez des soins médicaux de classe mondiale à une fraction du coût. Nos hôpitaux accrédités et nos médecins experts offrent des résultats exceptionnels.",
    "about.title": "À Propos de Sekhmet Wellness Journeys",
    "about.subtitle": "Votre Partenaire de Confiance en Tourisme Médical",
    "about.mission.title": "Notre Mission",
    "about.mission.text": "Nous connectons les patients internationaux aux meilleures installations médicales d'Égypte, garantissant des soins de santé de classe mondiale à des prix abordables avec une expérience de voyage fluide.",
    "about.vision.title": "Notre Vision",
    "about.vision.text": "Faire de l'Égypte la destination leader du tourisme médical, en combinant les traditions de guérison anciennes avec la médecine moderne de pointe.",
    "about.whyUs.title": "Pourquoi Nous Choisir",
    "about.whyUs.subtitle": "Ce Qui Nous Distingue",
    "about.whyUs.accredited": "Hôpitaux Accrédités JCI",
    "about.whyUs.accredited.desc": "Tous nos hôpitaux partenaires respectent les normes internationales les plus élevées en matière de sécurité et de qualité des soins.",
    "about.whyUs.savings": "Jusqu'à 85% d'Économies",
    "about.whyUs.savings.desc": "Bénéficiez de traitements de classe mondiale à une fraction du coût par rapport aux États-Unis, au Royaume-Uni et à l'Europe.",
    "about.whyUs.doctors": "Médecins Experts",
    "about.whyUs.doctors.desc": "Nos chirurgiens sont formés et certifiés internationalement avec des décennies d'expérience.",
    "about.whyUs.support": "Support 24h/24 7j/7",
    "about.whyUs.support.desc": "De votre première demande au suivi post-traitement, nous sommes à vos côtés à chaque étape.",
    "about.whyUs.travel": "Assistance Voyage Complète",
    "about.whyUs.travel.desc": "Nous gérons le support visa, les transferts aéroport, les réservations d'hôtel et le transport local.",
    "about.whyUs.language": "Équipe Multilingue",
    "about.whyUs.language.desc": "Notre équipe parle anglais, arabe, français et plus pour assurer une communication claire.",
    "about.story.title": "Notre Histoire",
    "about.story.text": "Fondée avec la passion de connecter les patients à des soins médicaux exceptionnels, Sekhmet Wellness Journeys est née de la conviction que des soins de santé de qualité doivent être accessibles à tous.",
    "about.team.title": "Notre Équipe",
    "about.team.subtitle": "Rencontrez les Experts Derrière Votre Voyage",
    "about.values.title": "Nos Valeurs",
    "about.values.quality": "Qualité",
    "about.values.trust": "Confiance",
    "about.values.care": "Soins",
    "about.values.transparency": "Transparence",
    "treatments.title": "Nos Traitements",
    "treatments.subtitle": "Procédures Médicales de Classe Mondiale en Égypte",
    "treatments.description": "Explorez notre gamme complète de traitements médicaux, tous réalisés par des médecins certifiés internationalement dans des hôpitaux accrédités JCI.",
    "treatments.dental.title": "Soins Dentaires",
    "treatments.dental.desc": "Implants, facettes, relooking sourire Hollywood et soins dentaires complets dans des installations de classe mondiale.",
    "treatments.hair.title": "Greffe de Cheveux",
    "treatments.hair.desc": "Techniques avancées de restauration capillaire FUE et DHI avec des résultats naturels.",
    "treatments.cosmetic.title": "Chirurgie Esthétique",
    "treatments.cosmetic.desc": "Rhinoplastie, lifting, liposuccion, abdominoplastie et remodelage corporel par des chirurgiens experts.",
    "treatments.eye.title": "Chirurgie des Yeux",
    "treatments.eye.desc": "LASIK, PRK, chirurgie de la cataracte et procédures avancées de correction visuelle.",
    "treatments.bariatric.title": "Chirurgie Bariatrique",
    "treatments.bariatric.desc": "Sleeve gastrique, bypass gastrique et chirurgie de perte de poids avec suivi complet.",
    "treatments.skin.title": "Peau & Esthétique",
    "treatments.skin.desc": "Botox, fillers, peelings chimiques, traitements laser et rajeunissement non chirurgical.",
    "treatments.fertility.title": "Traitements de Fertilité",
    "treatments.fertility.desc": "FIV, insémination intra-utérine, congélation d'ovocytes et services complets de médecine reproductive.",
    "treatments.startingFrom": "À partir de",
    "treatments.getQuote": "Devis Gratuit",
    "treatments.viewDetails": "Voir les Détails",
    "treatments.compareToUS": "par rapport aux prix américains",
    "treatments.savingsUpTo": "Économisez jusqu'à",
    "dentalCare.title": "Soins Dentaires en Égypte",
    "dentalCare.subtitle": "Traitements Dentaires de Classe Mondiale à Prix Abordables",
    "dentalCare.description": "Du nettoyage de routine aux procédures avancées, nos experts dentaires fournissent des soins complets avec les dernières technologies.",
    "dentalCare.whyEgypt": "Pourquoi Choisir l'Égypte pour les Soins Dentaires ?",
    "dentalCare.savings": "Économisez 75-88% par rapport aux prix US & UK",
    "dentalCare.quality": "Normes et matériaux de qualité internationale",
    "dentalCare.technology": "Dernières technologies et équipements dentaires",
    "dentalCare.experience": "Dentistes expérimentés formés internationalement",
    "dentalCare.services": "Nos Services Dentaires",
    "dentalCare.implants": "Implants Dentaires",
    "dentalCare.implants.desc": "Implants en titane premium avec garantie à vie, posés par des implantologues experts.",
    "dentalCare.veneers": "Facettes en Porcelaine",
    "dentalCare.veneers.desc": "Facettes sur mesure pour une transformation du sourire parfaite et naturelle.",
    "dentalCare.crowns": "Couronnes & Bridges",
    "dentalCare.crowns.desc": "Couronnes et bridges dentaires durables et esthétiques avec des matériaux premium.",
    "dentalCare.whitening": "Blanchiment Dentaire",
    "dentalCare.whitening.desc": "Traitements de blanchiment professionnels en cabinet et à domicile pour un sourire plus éclatant.",
    "dentalCare.rootCanal": "Traitement de Canal",
    "dentalCare.rootCanal.desc": "Traitement de canal sans douleur avec des instruments rotatifs avancés.",
    "dentalCare.orthodontics": "Orthodontie",
    "dentalCare.orthodontics.desc": "Appareils traditionnels et aligneurs transparents pour un alignement dentaire parfait.",
    "dentalImplants.title": "Implants Dentaires en Égypte",
    "dentalImplants.subtitle": "Implants Premium à 75-88% Moins Cher qu'aux États-Unis",
    "dentalImplants.description": "Obtenez des implants dentaires de classe mondiale par des implantologues certifiés internationalement utilisant des marques premium comme Nobel Biocare, Straumann et plus.",
    "dentalImplants.benefits.title": "Pourquoi les Implants Dentaires ?",
    "dentalImplants.benefits.permanent": "Solution Permanente",
    "dentalImplants.benefits.natural": "Aspect et Sensation Naturels",
    "dentalImplants.benefits.bone": "Préserve la Santé Osseuse",
    "dentalImplants.benefits.function": "Fonction de Mastication Complète",
    "dentalImplants.process.title": "Le Processus d'Implantation",
    "dentalImplants.process.consultation": "Consultation Gratuite & Scan 3D",
    "dentalImplants.process.placement": "Pose de l'Implant",
    "dentalImplants.process.healing": "Période de Cicatrisation",
    "dentalImplants.process.crown": "Pose de la Couronne",
    "dentalImplants.pricing.title": "Tarifs des Implants",
    "dentalImplants.pricing.single": "Implant Unique",
    "dentalImplants.pricing.allOn4": "All-on-4",
    "dentalImplants.pricing.allOn6": "All-on-6",
    "dentalImplants.pricing.fullMouth": "Restauration Complète",
    "hollywoodSmile.title": "Sourire Hollywood en Égypte",
    "hollywoodSmile.subtitle": "Transformez Votre Sourire avec des Facettes de Classe Mondiale",
    "hollywoodSmile.description": "Obtenez le sourire de célébrité parfait avec des facettes en porcelaine premium réalisées par les meilleurs dentistes esthétiques d'Égypte.",
    "hollywoodSmile.whatIs": "Qu'est-ce qu'un Sourire Hollywood ?",
    "hollywoodSmile.whatIs.desc": "Un Sourire Hollywood est un relooking complet du sourire utilisant des facettes en porcelaine ultra-fines pour créer un sourire parfaitement aligné et brillamment blanc.",
    "hollywoodSmile.process.title": "Votre Parcours Sourire",
    "hollywoodSmile.process.design": "Design Numérique du Sourire",
    "hollywoodSmile.process.prep": "Préparation des Dents",
    "hollywoodSmile.process.temp": "Facettes Temporaires",
    "hollywoodSmile.process.final": "Pose des Facettes Finales",
    "hollywoodSmile.benefits.title": "Avantages",
    "hollywoodSmile.benefits.instant": "Transformation Instantanée",
    "hollywoodSmile.benefits.durable": "Durabilité de 10-15 Ans",
    "hollywoodSmile.benefits.stain": "Résistant aux Taches",
    "hollywoodSmile.benefits.natural": "Apparence Naturelle",
    "fertility.title": "Traitements de Fertilité en Égypte",
    "fertility.subtitle": "Médecine Reproductive Avancée à Prix Abordables",
    "fertility.description": "Nos cliniques de fertilité offrent des services reproductifs complets incluant FIV, IIU et congélation d'ovocytes avec des taux de réussite élevés.",
    "fertility.services.title": "Nos Services de Fertilité",
    "fertility.ivf": "Fécondation In Vitro (FIV)",
    "fertility.ivf.desc": "Cycles FIV complets avec des laboratoires d'embryologie avancés et des spécialistes expérimentés.",
    "fertility.iui": "Insémination Intra-Utérine (IIU)",
    "fertility.iui.desc": "Traitement de fertilité moins invasif avec des procédures minutieusement programmées.",
    "fertility.eggFreezing": "Congélation d'Ovocytes",
    "fertility.eggFreezing.desc": "Préservez votre fertilité avec notre technologie de vitrification de pointe.",
    "fertility.genetic": "Tests Génétiques",
    "fertility.genetic.desc": "Tests génétiques préimplantatoires pour des grossesses plus saines.",
    "fertility.whyEgypt": "Pourquoi Choisir l'Égypte pour la Fertilité ?",
    "fertility.successRates": "Taux de Réussite Élevés",
    "fertility.affordability": "60-70% Plus Abordable",
    "fertility.privacy": "Confidentialité Totale",
    "fertility.technology": "Dernières Technologies",
    "howItWorks.title": "Comment Ça Marche",
    "howItWorks.subtitle": "Votre Voyage en 4 Étapes Simples",
    "howItWorks.description": "Nous rendons le tourisme médical simple, sûr et sans stress. Voici comment se déroule votre voyage.",
    "howItWorks.step1.title": "Consultation Gratuite",
    "howItWorks.step1.desc": "Partagez vos besoins médicaux et recevez un plan de traitement personnalisé avec des tarifs transparents sous 24 heures.",
    "howItWorks.step2.title": "Planifiez Votre Voyage",
    "howItWorks.step2.desc": "Nous organisons tout — vols, hôtel, transferts aéroport, rendez-vous hospitaliers et votre calendrier de traitement.",
    "howItWorks.step3.title": "Recevez Votre Traitement",
    "howItWorks.step3.desc": "Bénéficiez de soins de classe mondiale dans un hôpital accrédité JCI avec votre coordinateur patient dédié à vos côtés.",
    "howItWorks.step4.title": "Récupération & Suivi",
    "howItWorks.step4.desc": "Récupérez confortablement avec notre support de suivi, et profitez de consultations continues une fois de retour chez vous.",
    "howItWorks.cta": "Commencez Votre Voyage Aujourd'hui",
    "howItWorks.guarantee.title": "Notre Garantie",
    "howItWorks.guarantee.desc": "Nous soutenons chaque traitement avec notre garantie de satisfaction et notre support continu.",
    "doctors.title": "Nos Médecins",
    "doctors.subtitle": "Rencontrez les Spécialistes Médicaux Leaders d'Égypte",
    "doctors.description": "Notre équipe de médecins soigneusement sélectionnés est formée internationalement, certifiée et apporte des décennies d'expérience dans leurs spécialités.",
    "doctors.specialties": "Spécialités",
    "doctors.experience": "Années d'Expérience",
    "doctors.education": "Formation",
    "doctors.certifications": "Certifications",
    "doctors.languages": "Langues",
    "doctors.bookConsultation": "Réserver une Consultation",
    "doctors.viewProfile": "Voir le Profil",
    "doctors.qualifications": "Qualifications",
    "doctors.procedures": "Procédures Réalisées",
    "stories.title": "Témoignages Patients",
    "stories.subtitle": "Résultats Réels de Vrais Patients",
    "stories.description": "Découvrez les expériences des patients qui ont choisi l'Égypte pour leurs soins médicaux et ont transformé leur vie.",
    "stories.readStory": "Lire l'Histoire Complète",
    "stories.beforeAfter": "Avant & Après",
    "stories.treatment": "Traitement",
    "stories.country": "Pays",
    "stories.savings": "Économies",
    "stories.rating": "Évaluation",
    "stories.verified": "Patient Vérifié",
    "stories.shareYourStory": "Partagez Votre Histoire",
    "faq.title": "Questions Fréquemment Posées",
    "faq.subtitle": "Tout Ce Que Vous Devez Savoir",
    "faq.description": "Obtenez des réponses aux questions les plus courantes sur le tourisme médical en Égypte.",
    "faq.categories.general": "Général",
    "faq.categories.travel": "Voyage & Logistique",
    "faq.categories.medical": "Médical",
    "faq.categories.pricing": "Tarifs & Paiement",
    "faq.categories.aftercare": "Suivi",
    "faq.stillHaveQuestions": "Encore des Questions ?",
    "faq.contactUs": "Contactez-nous pour des réponses personnalisées",
    "faq.q1": "Le traitement médical en Égypte est-il sûr ?",
    "faq.a1": "Oui. Nos hôpitaux partenaires sont accrédités JCI, respectant les normes internationales les plus élevées en matière de sécurité des patients et de qualité des soins. Nos médecins sont formés et certifiés internationalement.",
    "faq.q2": "Combien puis-je économiser ?",
    "faq.a2": "Les patients économisent généralement 50-85% par rapport aux prix aux États-Unis, au Royaume-Uni et en Europe, selon la procédure.",
    "faq.q3": "Qu'est-ce qui est inclus dans le forfait de traitement ?",
    "faq.a3": "Nos forfaits incluent généralement la procédure médicale, le séjour hospitalier, les honoraires du chirurgien, les médicaments, les transferts aéroport, l'hébergement hôtelier et un coordinateur patient dédié.",
    "faq.q4": "Ai-je besoin d'un visa pour voyager en Égypte ?",
    "faq.a4": "La plupart des nationalités peuvent obtenir un visa à l'arrivée ou un e-visa. Nous fournissons une assistance visa complète dans le cadre de notre service.",
    "faq.q5": "Combien de temps devrai-je rester en Égypte ?",
    "faq.a5": "La durée dépend de votre traitement. La plupart des procédures dentaires nécessitent 5-7 jours, tandis que les interventions chirurgicales peuvent nécessiter 7-14 jours. Nous fournirons un calendrier détaillé lors de votre consultation.",
    "faq.q6": "Que se passe-t-il si j'ai des complications après mon retour ?",
    "faq.a6": "Nous fournissons un support de suivi complet incluant des consultations virtuelles avec votre médecin, et pouvons coordonner avec des médecins locaux dans votre pays si nécessaire.",
    "travelGuide.title": "Guide de Voyage en Égypte",
    "travelGuide.subtitle": "Tout Ce Dont Vous Avez Besoin pour Votre Voyage Médical",
    "travelGuide.description": "Planifiez votre voyage de tourisme médical en Égypte avec notre guide complet couvrant les visas, conseils de voyage, hébergement et plus.",
    "travelGuide.visa.title": "Informations Visa",
    "travelGuide.visa.desc": "La plupart des nationalités peuvent obtenir un visa à l'arrivée ou un e-visa. Nous fournissons une assistance visa complète.",
    "travelGuide.flights.title": "Comment S'y Rendre",
    "travelGuide.flights.desc": "L'aéroport international du Caire est bien connecté avec des vols directs depuis les grandes villes du monde.",
    "travelGuide.accommodation.title": "Hébergement",
    "travelGuide.accommodation.desc": "Des hôtels 5 étoiles luxueux aux appartements de récupération confortables près de l'hôpital.",
    "travelGuide.weather.title": "Climat & Météo",
    "travelGuide.weather.desc": "L'Égypte bénéficie d'un climat chaud toute l'année. Les meilleures périodes sont d'octobre à avril.",
    "travelGuide.currency.title": "Devise & Paiements",
    "travelGuide.currency.desc": "La livre égyptienne (EGP) est la monnaie locale. Les principales cartes de crédit sont largement acceptées.",
    "travelGuide.safety.title": "Sécurité & Sûreté",
    "travelGuide.safety.desc": "Les zones de tourisme médical en Égypte sont sûres et bien sécurisées. Nous fournissons un support 24h/24 pendant votre séjour.",
    "travelGuide.culture.title": "Culture & Attractions",
    "travelGuide.culture.desc": "Combinez votre voyage médical avec des visites aux Pyramides, Louxor et d'autres attractions mondialement célèbres.",
    "travelGuide.tips.title": "Conseils de Voyage",
    "travelGuide.packing": "Que Mettre dans Vos Bagages",
    "travelGuide.transport": "Transport Local",
    "travelGuide.food": "Nourriture & Restaurants",
    "travelGuide.communication": "Communication",
    "pricing.title": "Tarifs des Traitements",
    "pricing.subtitle": "Tarifs Transparents, Sans Frais Cachés",
    "pricing.description": "Comparez nos prix avec les coûts aux États-Unis et au Royaume-Uni. Tous les prix incluent la procédure, les frais hospitaliers et les honoraires du chirurgien.",
    "pricing.procedure": "Procédure",
    "pricing.egyptPrice": "Prix en Égypte",
    "pricing.usPrice": "Prix aux États-Unis",
    "pricing.ukPrice": "Prix au Royaume-Uni",
    "pricing.savings": "Économies",
    "pricing.allInclusive": "Forfait Tout Inclus",
    "pricing.includes": "Ce Qui Est Inclus",
    "pricing.getQuote": "Obtenir un Devis Personnalisé",
    "pricing.disclaimer": "Les prix sont approximatifs et peuvent varier selon les besoins individuels. Le tarif final est fourni après consultation.",
    "pricing.viewAll": "Voir Tous les Prix",
    "pricing.compareAndSave": "Comparez & Économisez",
    "pricing.categories.dental": "Dentaire",
    "pricing.categories.hair": "Greffe de Cheveux",
    "pricing.categories.cosmetic": "Chirurgie Esthétique",
    "pricing.categories.eye": "Chirurgie des Yeux",
    "pricing.categories.bariatric": "Chirurgie Bariatrique",
    "pricing.categories.skin": "Peau & Esthétique",
    "consultation.title": "Consultation Gratuite",
    "consultation.subtitle": "Obtenez Votre Plan de Traitement Personnalisé",
    "consultation.description": "Remplissez le formulaire ci-dessous et notre équipe médicale examinera votre cas et fournira un plan de traitement détaillé avec tarification sous 24 heures.",
    "consultation.form.name": "Nom Complet",
    "consultation.form.email": "Adresse Email",
    "consultation.form.phone": "Numéro de Téléphone",
    "consultation.form.country": "Pays",
    "consultation.form.treatment": "Traitement Souhaité",
    "consultation.form.message": "Décrivez vos besoins médicaux",
    "consultation.form.submit": "Soumettre la Demande de Consultation",
    "consultation.form.uploading": "Télécharger les Dossiers Médicaux (Optionnel)",
    "consultation.form.privacy": "Vos informations sont confidentielles et protégées.",
    "consultation.benefits.title": "Ce Que Vous Recevrez",
    "consultation.benefits.plan": "Plan de Traitement Personnalisé",
    "consultation.benefits.pricing": "Détail des Coûts",
    "consultation.benefits.timeline": "Calendrier de Traitement",
    "consultation.benefits.doctor": "Recommandations de Médecins",
    "consultation.response": "Nous répondons généralement sous 24 heures",
    "contact.title": "Contactez-Nous",
    "contact.subtitle": "Nous Sommes Là pour Vous Aider",
    "contact.description": "Des questions ? Contactez-nous par l'un des canaux ci-dessous.",
    "contact.form.name": "Votre Nom",
    "contact.form.email": "Votre Email",
    "contact.form.subject": "Sujet",
    "contact.form.message": "Votre Message",
    "contact.form.send": "Envoyer le Message",
    "contact.info.phone": "Téléphone",
    "contact.info.email": "Email",
    "contact.info.address": "Adresse",
    "contact.info.hours": "Heures d'Ouverture",
    "contact.info.whatsapp": "WhatsApp",
    "contact.followUs": "Suivez-Nous",
    "blog.title": "Blog",
    "blog.subtitle": "Perspectives & Conseils sur le Tourisme Médical",
    "blog.description": "Restez informé avec les dernières actualités, conseils et perspectives sur le tourisme médical en Égypte.",
    "blog.readTime": "min de lecture",
    "blog.category": "Catégorie",
    "blog.recentPosts": "Articles Récents",
    "blog.allPosts": "Tous les Articles",
    "blog.searchPosts": "Rechercher des articles...",
    "blog.noResults": "Aucun article trouvé",
    "blog.backToBlog": "Retour au Blog",
    "footer.description": "Votre partenaire de confiance pour des soins médicaux de classe mondiale en Égypte. Économisez jusqu'à 85% sur les traitements dans des hôpitaux accrédités JCI.",
    "footer.quickLinks": "Liens Rapides",
    "footer.treatments": "Traitements",
    "footer.aboutUs": "À Propos",
    "footer.contactUs": "Contactez-Nous",
    "footer.legal": "Mentions Légales",
    "footer.privacy": "Politique de Confidentialité",
    "footer.terms": "Conditions d'Utilisation",
    "footer.disclaimer": "Avertissement Médical",
    "footer.connect": "Connectez-vous",
    "footer.newsletter": "Newsletter",
    "footer.newsletter.placeholder": "Entrez votre email",
    "footer.newsletter.subscribe": "S'abonner",
    "footer.newsletter.desc": "Recevez les dernières mises à jour sur les traitements et offres spéciales.",
    "footer.copyright": "© 2026 Sekhmet Wellness Journeys. Tous droits réservés.",
    "footer.accredited": "Partenaire Accrédité JCI",
    "common.loading": "Chargement...",
    "common.error": "Une erreur est survenue",
    "common.tryAgain": "Réessayer",
    "common.back": "Retour",
    "common.next": "Suivant",
    "common.previous": "Précédent",
    "common.submit": "Soumettre",
    "common.cancel": "Annuler",
    "common.save": "Enregistrer",
    "common.yes": "Oui",
    "common.no": "Non",
    "common.or": "ou",
    "common.and": "et",
    "common.free": "Gratuit",
    "common.from": "À partir de",
    "common.perMonth": "par mois",
    "common.patients": "Patients",
    "common.reviews": "Avis",
    "common.stars": "Étoiles",
    "common.viewMore": "Voir Plus",
    "common.callNow": "Appelez Maintenant",
    "common.whatsapp": "WhatsApp",
    "common.email": "Envoyez-nous un Email",
    "common.phone": "Téléphone",
    "common.address": "Adresse",
    "trust.jciAccredited": "Accrédité JCI",
    "trust.patientsServed": "Patients Servis",
    "trust.successRate": "Taux de Réussite",
    "trust.yearsExperience": "Années d'Expérience",
    "trust.countriesServed": "Pays Servis",
    "trust.satisfaction": "Satisfaction Patient",
    "trust.support247": "Support 24h/24",
    "trust.moneyBack": "Garantie de Satisfaction",
    "trust.freeConsultation": "Consultation Gratuite",
    "trust.noHiddenFees": "Sans Frais Cachés",
    "cta.readyToStart": "Prêt à Commencer Votre Voyage ?",
    "cta.getStartedToday": "Commencez Aujourd'hui",
    "cta.freeQuote": "Obtenez Votre Devis Gratuit",
    "cta.scheduleCall": "Planifier un Appel",
    "cta.talkToExpert": "Parler à un Expert",
    "cta.startSaving": "Commencez à Économiser",
    "cta.compareAndSave": "Comparez & Économisez",
    "cta.bookConsultation": "Réservez une Consultation Gratuite",
    "cta.noObligation": "Sans engagement. 100% gratuit.",
    "cta.responseTime": "Réponse sous 24 heures",
    "calculator.title": "Calculateur de Coûts",
    "calculator.subtitle": "Estimez Vos Économies",
    "calculator.selectTreatment": "Sélectionner le Traitement",
    "calculator.yourCountry": "Votre Pays",
    "calculator.estimatedCost": "Coût Estimé en Égypte",
    "calculator.typicalCost": "Coût Typique dans Votre Pays",
    "calculator.youSave": "Vous Économisez",
    "calculator.includes": "Le Prix Inclut",
    "calculator.note": "Le prix final est déterminé après consultation",
    "specialties.title": "Nos Spécialités",
    "specialties.subtitle": "Soins Médicaux Complets",
    "specialties.explore": "Explorer"
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');
  const [direction, setDirection] = useState<Direction>('ltr');

  useEffect(() => {
    const newDir = language === 'ar' ? 'rtl' : 'ltr';
    setDirection(newDir);
    document.documentElement.dir = newDir;
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, direction, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
